module lang::flybytes::tests::DecompileTests

import lang::flybytes::Decompiler;

@ignore{have to fix with Java 11 generated bytecode}
test bool fullyDecompileRoundtripClass()
  = /asm(_) !:= decompile(|target://flybytes/lang/flybytes/tests/examples/RoundtripTestClass.class|);
  
@ignore{have to fix with Java 11 generated bytecode}  
test bool fullyDecompileBankClass()
  = /asm(_) !:= decompile(|target://flybytes/lang/flybytes/tests/examples/business/Bank.class|);  
   
test bool fullyDecompileAccountClass()
  = /asm(_) !:= decompile(|target://flybytes/lang/flybytes/tests/examples/business/Account.class|);  